export const language_table = [
  {
    id: 1,
    code: "en",
    pt_name: "inglês",
    es_name: "inglés",
    en_name: "English",
    tag: "en",
  },
  {
    id: 2,
    code: "es",
    pt_name: "espanhol",
    es_name: "España",
    en_name: "Spanish",
    tag: "es-ES",
  },
  {
    id: 3,
    code: "de",
    pt_name: "alemão",
    es_name: "alemán",
    en_name: "German",
    tag: "de",
  },
  {
    id: 4,
    code: "fr",
    pt_name: "francês",
    es_name: "francés",
    en_name: "French",
    tag: "fr",
  },
  {
    id: 5,
    code: "ar",
    pt_name: "argentina",
    es_name: "argentina",
    en_name: "argentinian",
    tag: "es-AR",
  },
  {
    id: 6,
    code: "bs",
    pt_name: "Bósnio",
    es_name: "bosnio",
    en_name: "Bosnian",
    tag: "bs",
  },
  {
    id: 7,
    code: "bg",
    pt_name: "búlgaro",
    es_name: "búlgaro",
    en_name: "Bulgarian",
    tag: "bg",
  },
  {
    id: 8,
    code: "ca",
    pt_name: "catalão",
    es_name: "catalán",
    en_name: "Catalan",
    tag: "ca",
  },
  {
    id: 9,
    code: "cs",
    pt_name: "Tcheco",
    es_name: "checo",
    en_name: "Czech",
    tag: "cs",
  },
  {
    id: 10,
    code: "sk",
    pt_name: "Eslovaco",
    es_name: "eslovaco",
    en_name: "Slovak",
    tag: "sk",
  },
  {
    id: 11,
    code: "cy",
    pt_name: "galês",
    es_name: "galés",
    en_name: "Welsh",
    tag: "cy",
  },
  {
    id: 12,
    code: "da",
    pt_name: "dinamarquês",
    es_name: "danés",
    en_name: "Danish",
    tag: "da",
  },
  {
    id: 13,
    code: "el",
    pt_name: "grego",
    es_name: "griego",
    en_name: "Greek",
    tag: "el",
  },
  {
    id: 14,
    code: "eo",
    pt_name: "esperanto",
    es_name: "esperanto",
    en_name: "Esperanto",
    tag: "eo",
  },
  {
    id: 15,
    code: "et",
    pt_name: "estoniano",
    es_name: "Estonio",
    en_name: "Estonian",
    tag: "et",
  },
  {
    id: 16,
    code: "eu",
    pt_name: "Basco",
    es_name: "vasco",
    en_name: "Basque",
    tag: "eu",
  },
  {
    id: 17,
    code: "fa",
    pt_name: "persa",
    es_name: "persa",
    en_name: "Persian",
    tag: "fa",
  },
  {
    id: 18,
    code: "fi",
    pt_name: "finlandês",
    es_name: "finlandés",
    en_name: "Finnish",
    tag: "fi",
  },
  {
    id: 19,
    code: "ga",
    pt_name: "irlandês",
    es_name: "irlandesa",
    en_name: "Irish",
    tag: "ga",
  },
  {
    id: 20,
    code: "he",
    pt_name: "hebraico",
    es_name: "hebreo",
    en_name: "Hebrew",
    tag: "he",
  },
  {
    id: 21,
    code: "hi",
    pt_name: "hindi",
    es_name: "hindi",
    en_name: "Hindi",
    tag: "hi",
  },
  {
    id: 22,
    code: "hr",
    pt_name: "croata",
    es_name: "croata",
    en_name: "Croatian",
    tag: "hr",
  },
  {
    id: 23,
    code: "hu",
    pt_name: "húngaro",
    es_name: "húngaro",
    en_name: "Hungarian",
    tag: "hu",
  },
  {
    id: 24,
    code: "hy",
    pt_name: "Armênio",
    es_name: "armenio",
    en_name: "Armenian",
    tag: "hy",
  },
  {
    id: 25,
    code: "id",
    pt_name: "indonésio",
    es_name: "indonesio",
    en_name: "Indonesian",
    tag: "id",
  },
  {
    id: 26,
    code: "is",
    pt_name: "islandês",
    es_name: "islandés",
    en_name: "Icelandic",
    tag: "is",
  },
  {
    id: 27,
    code: "it",
    pt_name: "italiano",
    es_name: "italiano",
    en_name: "Italian",
    tag: "it",
  },
  {
    id: 28,
    code: "ja",
    pt_name: "japonês",
    es_name: "japonés",
    en_name: "Japanese",
    tag: "ja",
  },
  {
    id: 29,
    code: "ko",
    pt_name: "coreano",
    es_name: "coreano",
    en_name: "Korean",
    tag: "ko",
  },
  {
    id: 30,
    code: "ku",
    pt_name: "curdo",
    es_name: "kurdo",
    en_name: "Kurdish",
    tag: "ku",
  },
  {
    id: 31,
    code: "la",
    pt_name: "Latina",
    es_name: "latín",
    en_name: "Latin",
    tag: "la",
  },
  {
    id: 32,
    code: "lv",
    pt_name: "letão",
    es_name: "letón",
    en_name: "Latvian",
    tag: "lv",
  },
  {
    id: 33,
    code: "lt",
    pt_name: "lituano",
    es_name: "lituano",
    en_name: "Lithuanian",
    tag: "lt",
  },
  {
    id: 34,
    code: "mk",
    pt_name: "Macedônio",
    es_name: "macedónio",
    en_name: "Macedonian",
    tag: "mk",
  },
  {
    id: 35,
    code: "mt",
    pt_name: "maltês",
    es_name: "maltés",
    en_name: "Maltese",
    tag: "mt",
  },
  {
    id: 36,
    code: "mn",
    pt_name: "mongol",
    es_name: "mongol",
    en_name: "Mongolian",
    tag: "mn",
  },
  {
    id: 37,
    code: "ne",
    pt_name: "Nepalês",
    es_name: "Nepalí",
    en_name: "Nepali",
    tag: "ne",
  },
  {
    id: 38,
    code: "nl",
    pt_name: "holandês",
    es_name: "holandés",
    en_name: "Dutch",
    tag: "nl",
  },
  {
    id: 39,
    code: "no",
    pt_name: "Bokmål norueguês",
    es_name: "Noruego bokmål",
    en_name: "Norwegian Bokmål",
    tag: "no",
  },
  {
    id: 40,
    code: "pa",
    pt_name: "Punjabi",
    es_name: "punjabi",
    en_name: "Punjabi",
    tag: "pa",
  },
  {
    id: 41,
    code: "pl",
    pt_name: "polonês",
    es_name: "polaco",
    en_name: "Polish",
    tag: "pl",
  },
  {
    id: 42,
    code: "pt-pt",
    pt_name: "Portugues, portugal",
    es_name: "Portugués, portugal",
    en_name: "Portuguese, Portugal",
    tag: "pt-pt",
  },
  {
    id: 43,
    code: "pt-br",
    pt_name: "Portugues brasil",
    es_name: "Portugués, brasil",
    en_name: "Portuguese, Brazil",
    tag: "pt-br",
  },
  {
    id: 44,
    code: "qu",
    pt_name: "Quechua",
    es_name: "quechua",
    en_name: "Quechua",
    tag: "qu",
  },
  {
    id: 45,
    code: "ro",
    pt_name: "romena",
    es_name: "rumano",
    en_name: "Romanian",
    tag: "ro",
  },
  {
    id: 46,
    code: "ru",
    pt_name: "russo",
    es_name: "ruso",
    en_name: "Russian",
    tag: "ru",
  },
  {
    id: 47,
    code: "sl",
    pt_name: "esloveno",
    es_name: "esloveno",
    en_name: "Slovenian",
    tag: "sl",
  },
  {
    id: 48,
    code: "so",
    pt_name: "Somali",
    es_name: "somalí",
    en_name: "Somali",
    tag: "so",
  },
  {
    id: 49,
    code: "sq",
    pt_name: "albanês",
    es_name: "albanés",
    en_name: "Albanian",
    tag: "sq",
  },
  {
    id: 50,
    code: "sr",
    pt_name: "sérvio",
    es_name: "serbio",
    en_name: "Serbian",
    tag: "sr",
  },
  {
    id: 51,
    code: "sv",
    pt_name: "sueco",
    es_name: "sueco",
    en_name: "Swedish",
    tag: "sv",
  },
  {
    id: 52,
    code: "ta",
    pt_name: "tâmil",
    es_name: "Tamil",
    en_name: "Tamil",
    tag: "ta",
  },
  {
    id: 53,
    code: "th",
    pt_name: "tailandês",
    es_name: "tailandés",
    en_name: "Thai",
    tag: "th",
  },
  {
    id: 54,
    code: "tr",
    pt_name: "turco",
    es_name: "turco",
    en_name: "Turkish",
    tag: "tr",
  },
  {
    id: 55,
    code: "uk",
    pt_name: "ucraniano",
    es_name: "ucranio",
    en_name: "Ukrainian",
    tag: "uk",
  },
  {
    id: 56,
    code: "ur",
    pt_name: "urdu",
    es_name: "Urdu",
    en_name: "Urdu",
    tag: "ur",
  },
  {
    id: 57,
    code: "uz",
    pt_name: "Uzbeque",
    es_name: "Uzbeko",
    en_name: "Uzbek",
    tag: "uz",
  },
  {
    id: 58,
    code: "vi",
    pt_name: "vietnamita",
    es_name: "vietnamita",
    en_name: "Vietnamese",
    tag: "vi",
  },
  {
    id: 59,
    code: "yi",
    pt_name: "Iídiche",
    es_name: "yídish",
    en_name: "Yiddish",
    tag: "yi",
  },
  {
    id: 60,
    code: "zh-hans",
    pt_name: "Chinês simplificado)",
    es_name: "Chino simplificado)",
    en_name: "Chinese (Simplified)",
    tag: "zh-hans",
  },
  {
    id: 61,
    code: "zu",
    pt_name: "zulu",
    es_name: "zulú",
    en_name: "Zulu",
    tag: "zu",
  },
  {
    id: 62,
    code: "zh-hant",
    pt_name: "Chinês tradicional)",
    es_name: "Chino tradicional)",
    en_name: "Chinese (Traditional)",
    tag: "zh-hant",
  },
  {
    id: 63,
    code: "ms",
    pt_name: "malaio",
    es_name: "malayo",
    en_name: "Malay",
    tag: "ms",
  },
  {
    id: 64,
    code: "ha",
    pt_name: "América hispânica",
    es_name: "América hispana",
    en_name: "hispano america",
    tag: "cl2",
  },
  {
    id: 65,
    code: "mx",
    pt_name: "México",
    es_name: "México",
    en_name: "México",
    tag: "es-MX",
  },
  {
    id: 66,
    code: "cl",
    pt_name: "Pimenta",
    es_name: "chile",
    en_name: "Chile",
    tag: "es-CL",
  },
  {
    id: 67,
    code: "pe",
    pt_name: "Peru",
    es_name: "Perú",
    en_name: "Perú",
    tag: "es-PE",
  },
  {
    id: 68,
    code: "co",
    pt_name: "Colômbia",
    es_name: "Colombia",
    en_name: "Colombia",
    tag: "es-CO",
  },
];
